# Generated by Django 6.0 on 2025-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosamplemodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
